### ISSUE TITLE
Git checkout fails

### ISSUE THREAD

**Issue by lordfolken** [hor63/horOpenVario#4]
The recursive git checkout fails with:

fatal: remote error: upload-pack: not our ref 840658b093976390e9537724f802281c9c8439f5
Fetched in submodule path 'src/uboot-mainline', but it did not contain 840658b093976390e9537724f802281c9c8439f5. Direct fetching of that commit failed.

**Comment by hor63** [comment]
That is fixed with commit 103f7789858f8c69f0846754172d995f15ddff78
