### ISSUE TITLE
fdisk is missing from build-packages.txt

### ISSUE THREAD

**Issue by roeles** [hor63/horOpenVario#5]

**Comment by roeles** [comment]
And probably more.
I'm trying to build inside a Docker image now, starting with just:

```
FROM debian:bullseye
RUN apt-get update
RUN apt-get -y install git
 git clone https://github.com/hor63/horOpenVario.git --recursive
 ```
 And then manually running ```./makenewimage.sh --no-pause```
 You then easily see fundamental things like ```sudo``` and ```fdisk``` popping up.
 
 Once I have a complete list, I'll probably send you a PR.

**Comment by hor63** [comment]
I started in a chroot environment with a Ubuntu deboostrap installation which installs a basic working system with the base essentials like fdisk and sudo packages installed.

When you are starting at a lower level there may be more packages to install. Please send a pull-request with these missing packages added.

**Comment by roeles** [comment]
/dev/loop5 is unusable inside docker, so that also renders this issue
useless for now.

**Comment by hor63** [comment]
I am not using docker.
I am using the loopback interface to map the SD card image as block device and partion it, setup the file systems, and mount
them to install the OS with debootstrap.
Loopback devices are therefore an integral part of this setup.

**Comment by hor63** [comment]
Haha, overlooked the original text of this issue:
The package "fdisk" is indeed missing by default in Debian (in Ubuntu deboostraps it is by default installed).
Done with commit [9dfdcb6](https://github.com/hor63/horOpenVario/commit/9dfdcb62bffb6b5e04525a4d819c95306af97eeb).
