### ISSUE TITLE
Use noatime in fstab

### ISSUE THREAD

**Issue by roeles** [hor63/horOpenVario#7]
I see ```nodiratime``` used in fstab. I wonder why this is not ```noatime```?
This causes a write for every read, causing wear on the SD card. Is there something that relies on properly administrated ```atime``` file attributes?

**Comment by hor63** [comment]
`nodiratime` was the more conservative option.
Reading a bit more access time is used nowhere except in rare circumstances (backup programs, and some mailers).
None is my concern.

Thanks for the suggestion.

**Comment by hor63** [comment]
Implemented with commit [76fcc50caff7e339583c6c30a07cc226a530d7a5](https://github.com/hor63/horOpenVario/commit/76fcc50caff7e339583c6c30a07cc226a530d7a5)
